name: ASP.NET Core Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./backend/backend.csproj

      - name: Build project
        run: dotnet build ./backend/backend.csproj --configuration Release

      - name: Run tests
        run: dotnet test ./backend/backend.csproj --configuration Release --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish ./backend/backend.csproj --configuration Release --output ./publish
